Algoritmo "PrimeiroAlgoritmo"
// Disciplina  : Algoritmos e Lógica de Programação
// Professor   : Nelio Alves - Udemy
// Descrição   : Primeira Atividade! (Hello Word)
// Autor(a)    : Aluno João Lucas M Mendes
// Data atual  : 16/03/2021
Var
// Seção de Declarações das variáveis, não usada nesta atividade.


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Hello Word")


Fimalgoritmo